# Generated by Django 4.2.23 on 2025-07-31 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionID', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('updateCount', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(choices=[(-1, 'None Specified'), (0, 'Easy'), (1, 'Medium'), (2, 'Hard'), (3, 'Insane')], default=-1)),
                ('approved', models.IntegerField(choices=[(0, 'Draft'), (1, 'Not Approved'), (2, 'Approved')], default=0)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
