# Generated by Django 4.2.23 on 2025-08-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='approved',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending Approval'), (2, 'Approved'), (3, 'Disapproved')], default=0),
        ),
    ]
